
BASE = ../../rai

DEPEND = Core Algo Kin Gui Geo KOMO Optim 

OBJS = main.o

GL = 1

CPATHS += /usr/include/eigen3
CPATHS += /home/jay/ompl/src
LIBS += -Wl,-rpath,</home/jay/ompl/src> -L</home/jay/ompl/src> -lompl







include $(BASE)/build/generic.mk
